db.user_profile.insert([
  {
    _id:100,
    "user_id":1,
    "Firstname":"Dima",
    "Surname":"Pupkin",
    "phone":292483911,
    "photo":"D:\Study\SB\Photo.jpg"
  },
  {
    _id:101,
    "user_id":2,
    "Firstname":"Nikolay",
    "Surname":"Michailove",
    "phone":292493912,
    "photo":"NO"
  },
  {
    _id:103,
    "user_id":3,
    "Firstname":"Anna",
    "Surname":"Gjoli",
    "phone":292493948,
    "photo":"NO"
  },
  {
    _id:104,
    "user_id":4,
    "Firstname":"Vasa",
    "Surname":"Motors",
    "phone":292412948,
    "photo":"NO"
  },
  {
    _id:105,
    "user_id":5,
    "Firstname":"Igor",
    "Surname":"Kozlove",
    "phone":292412948,
    "photo":"NO"
  }
])
